export const invocationSample1 = [
  {
    id: 'bbf3813b-d02a-4e6d-b55b-d1c23bdf23b4',
    applicationId: 'aws:lambda:eu-west-1:77',
    applicationName: 'java-prod',
    traceId: '1-6411a931-5ce3583012a68c407907d29f',
    transactionId: 'f5c1378e-ce2e-44ad-ba46-ce9828c7adae',
    domainName: 'API',
    className: 'AWS-Lambda',
    operationName: 'java-prod',
    startTimestamp: 1678879025821,
    finishTimestamp: 1678879025939,
    duration: 118,
  },
  {
    id: '2cfa95be-9573-4512-b29e-f706e2372b53',
    applicationId: 'aws:lambda:eu-west-1:77',
    applicationName: 'java-prod',
    traceId: '1-6411a931-5ce3583012a68c407907d29f',
    transactionId: 'f5c1378e-ce2e-44ad-ba46-ce9828c7adae',
    domainName: '',
    className: 'Method',
    parentSpanId: 'bbf3813b-d02a-4e6d-b55b-d1c23bdf23b4',
    operationName: 'handler.team',
    startTimestamp: 1678879025821,
    finishTimestamp: 1678879025821,
    duration: 0,
    tags: {
      'method.return_value': {
        type: 'java.lang.String',
        value: "TeamGetRequest{callerId='8fd51b67-0d9b-400b-ae6b-df0c3f2c3ba0', id='3'}",
      },
      'method.args': [],
    },
  },
  {
    id: 'b4d8fb50-f1b1-4353-8729-900496248581',
    applicationId: 'aws:lambda:eu-west-1:77',
    applicationName: 'java-prod',
    traceId: '1-6411a931-5ce3583012a68c407907d29f',
    transactionId: 'f5c1378e-ce2e-44ad-ba46-ce9828c7adae',
    domainName: '',
    className: 'Method',
    parentSpanId: 'bbf3813b-d02a-4e6d-b55b-d1c23bdf23b4',
    operationName: 'getCallerId',
    startTimestamp: 1678879025821,
    finishTimestamp: 1678879025821,
    duration: 0,
    tags: {
      'method.return_value': { type: 'java.lang.String', value: '8fd51b67-0d9b-400b-ae6b-df0c3f2c3ba0' },
      'method.args': [],
    },
  },
  {
    id: 'd3f1dab9-9321-4e59-8ec9-6b203211578e',
    applicationId: 'aws:lambda:eu-west-1:77',
    applicationName: 'java-prod',
    traceId: '1-6411a931-5ce3583012a68c407907d29f',
    transactionId: 'f5c1378e-ce2e-44ad-ba46-ce9828c7adae',
    domainName: '',
    className: 'Method',
    parentSpanId: 'bbf3813b-d02a-4e6d-b55b-d1c23bdf23b4',
    operationName: 'getId',
    startTimestamp: 1678879025821,
    finishTimestamp: 1678879025821,
    duration: 0,
    tags: { 'method.return_value': { type: 'java.lang.String', value: '3' }, 'method.args': [] },
  },
  {
    id: '9a23a36a-d32b-496e-bb00-f7602661705a',
    applicationId: 'aws:lambda:eu-west-1:77',
    applicationName: 'java-prod',
    traceId: '1-6411a931-5ce3583012a68c407907d29f',
    transactionId: 'f5c1378e-ce2e-44ad-ba46-ce9828c7adae',
    domainName: '',
    className: 'Method',
    parentSpanId: 'bbf3813b-d02a-4e6d-b55b-d1c23bdf23b4',
    operationName: 'get',
    startTimestamp: 1678879025821,
    finishTimestamp: 1678879025939,
    duration: 118,
    tags: {
      'method.lines': [
        { duration: 0, line: 114, localVars: [{ name: 'id', type: 'java.lang.String', value: '3' }] },
        {
          duration: 0,
          line: 115,
          localVars: [
            { name: 'id', type: 'java.lang.String', value: '3' },
            { name: 'teamIdTagValue', type: 'java.lang.String', value: '3' },
          ],
        },
        {
          duration: 0,
          line: 117,
          localVars: [
            { name: 'id', type: 'java.lang.String', value: '3' },
            { name: 'teamIdTagValue', type: 'java.lang.String', value: '3' },
            { name: 'operationTypeTagValue', type: 'java.lang.String', value: 'team.get' },
          ],
        },
        {
          duration: 0,
          line: 118,
          localVars: [
            { name: 'id', type: 'java.lang.String', value: '3' },
            { name: 'teamIdTagValue', type: 'java.lang.String', value: '3' },
            { name: 'operationTypeTagValue', type: 'java.lang.String', value: 'team.get' },
          ],
        },
        {
          duration: 0,
          line: 120,
          localVars: [
            { name: 'id', type: 'java.lang.String', value: '3' },
            { name: 'teamIdTagValue', type: 'java.lang.String', value: '3' },
            { name: 'operationTypeTagValue', type: 'java.lang.String', value: 'team.get' },
          ],
        },
        {
          duration: 3,
          nextSpanIds: ['e0bc5610-7558-4340-b804-d4e398243098'],
          line: 122,
          localVars: [
            { name: 'id', type: 'java.lang.String', value: '3' },
            { name: 'teamIdTagValue', type: 'java.lang.String', value: '3' },
            { name: 'operationTypeTagValue', type: 'java.lang.String', value: 'team.get' },
          ],
        },
        {
          duration: 6,
          nextSpanIds: ['7eaafb4a-15d9-4589-b33f-ad669f255ee4'],
          line: 124,
          localVars: [
            { name: 'id', type: 'java.lang.String', value: '3' },
            { name: 'teamIdTagValue', type: 'java.lang.String', value: '3' },
            { name: 'operationTypeTagValue', type: 'java.lang.String', value: 'team.get' },
          ],
        },
        {
          duration: 0,
          line: 126,
          localVars: [
            { name: 'id', type: 'java.lang.String', value: '3' },
            { name: 'teamIdTagValue', type: 'java.lang.String', value: '3' },
            { name: 'operationTypeTagValue', type: 'java.lang.String', value: 'team.get' },
            { name: 'team' },
          ],
        },
        {
          duration: 56,
          nextSpanIds: ['40e08b9e-4b84-444a-a7c5-ee2359db680e'],
          line: 127,
          localVars: [
            { name: 'id', type: 'java.lang.String', value: '3' },
            { name: 'teamIdTagValue', type: 'java.lang.String', value: '3' },
            { name: 'operationTypeTagValue', type: 'java.lang.String', value: 'team.get' },
            { name: 'team' },
          ],
        },
        {
          duration: 0,
          line: 130,
          localVars: [
            { name: 'id', type: 'java.lang.String', value: '3' },
            { name: 'teamIdTagValue', type: 'java.lang.String', value: '3' },
            { name: 'operationTypeTagValue', type: 'java.lang.String', value: 'team.get' },
            {
              name: 'team',
              type: 'Team',
              value: { creationTime: 1678877820177, name: 'Team-643358844', id: '3' },
            },
          ],
        },
        {
          duration: 50,
          nextSpanIds: ['32450ee9-8ab1-4cf3-ac45-c33861c4bae3'],
          line: 131,
          localVars: [
            { name: 'id', type: 'java.lang.String', value: '3' },
            { name: 'teamIdTagValue', type: 'java.lang.String', value: '3' },
            { name: 'operationTypeTagValue', type: 'java.lang.String', value: 'team.get' },
            {
              name: 'team',
              type: 'Team',
              value: { creationTime: 1678877820177, name: 'Team-643358844', id: '3' },
            },
          ],
        },
        {
          duration: 0,
          line: 134,
          localVars: [
            { name: 'id', type: 'java.lang.String', value: '3' },
            { name: 'teamIdTagValue', type: 'java.lang.String', value: '3' },
            { name: 'operationTypeTagValue', type: 'java.lang.String', value: 'team.get' },
            {
              name: 'team',
              type: 'Team',
              value: { creationTime: 1678877820177, name: 'Team-643358844', id: '3' },
            },
          ],
        },
        {
          duration: 0,
          line: 136,
          localVars: [
            { name: 'id', type: 'java.lang.String', value: '3' },
            { name: 'teamIdTagValue', type: 'java.lang.String', value: '3' },
            { name: 'operationTypeTagValue', type: 'java.lang.String', value: 'team.get' },
            {
              name: 'team',
              type: 'Team',
              value: { creationTime: 1678877820177, name: 'Team-643358844', id: '3' },
            },
          ],
        },
        {
          duration: 0,
          line: 140,
          localVars: [
            { name: 'id', type: 'java.lang.String', value: '3' },
            { name: 'teamIdTagValue', type: 'java.lang.String', value: '3' },
            { name: 'operationTypeTagValue', type: 'java.lang.String', value: 'team.get' },
            {
              name: 'team',
              type: 'Team',
              value: { creationTime: 1678877820177, name: 'Team-643358844', id: '3' },
            },
          ],
        },
        {
          duration: 0,
          line: 142,
          localVars: [
            { name: 'id', type: 'java.lang.String', value: '3' },
            { name: 'teamIdTagValue', type: 'java.lang.String', value: '3' },
            { name: 'operationTypeTagValue', type: 'java.lang.String', value: 'team.get' },
            {
              name: 'team',
              type: 'Team',
              value: { creationTime: 1678877820177, name: 'Team-643358844', id: '3' },
            },
          ],
        },
      ],
      'method.return_value': {
        type: 'Team',
        value: { creationTime: 1678877820177, name: 'Team-643358844', id: '3' },
      },
      'method.args': [{ name: 'id', type: 'java.lang.String', value: '3' }],
      'method.startLine': 112,
      'method.source':
        '    public Team get(String id) {\n        try {\n            String teamIdTagValue = id;\n            String operationTypeTagValue = "team.get";\n\n            InvocationSupport.setTag("team.id", teamIdTagValue);\n            InvocationSupport.setTag("operation.type", operationTypeTagValue);\n\n            logger.info(String.format("Team with id %s has been requested", id));\n\n            validateId(id);\n\n            Team team = getFromCache(id);\n\n            if (team == null) {\n                team = teamRepository.get(id);\n            }\n\n            if (team != null) {\n                searchTeamProfile(id);\n            }\n\n            logger.info(String.format("Team with id %s has been retrieved: %s", id, team));\n\n            if (team == null) {\n                logger.warn(String.format("Team with id %s could not be found for retrieving", id, team));\n            }\n\n            InvocationSupport.setTag("operation.success", team != null);\n\n            return team;\n        } catch (Throwable t) {\n            InvocationSupport.setTag("operation.success", false);\n            ExceptionUtils.sneakyThrow(t);\n            return null;\n        }\n    }\n',
    },
  },
  {
    id: 'e0bc5610-7558-4340-b804-d4e398243098',
    applicationId: 'aws:lambda:eu-west-1:77',
    applicationName: 'java-prod',
    traceId: '1-6411a931-5ce3583012a68c407907d29f',
    transactionId: 'f5c1378e-ce2e-44ad-ba46-ce9828c7adae',
    domainName: '',
    className: 'Method',
    parentSpanId: '9a23a36a-d32b-496e-bb00-f7602661705a',
    operationName: 'validateId ',
    startTimestamp: 1678879025822,
    finishTimestamp: 1678879025825,
    duration: 3,
    tags: {
      'method.lines': [
        { duration: 3, line: 81, localVars: [{ name: 'id', type: 'java.lang.String', value: '3' }] },
        {
          duration: 0,
          nextSpanIds: ['31f706b0-3d45-47ec-b87c-0ec6131ff766'],
          line: 83,
          localVars: [{ name: 'id', type: 'java.lang.String', value: '3' }],
        },
        { duration: 0, line: 84, localVars: [{ name: 'id', type: 'java.lang.String', value: '3' }] },
      ],
      'method.return_value': {},
      'method.args': [{ name: 'id', type: 'java.lang.String', value: '3' }],
      'method.startLine': 80,
      'method.source':
        '    private void validateId(String id) {\n        doProcess(5);\n\n        validateNotEmptyString(id, "Team id cannot be empty!");\n    }\n',
    },
  },
  {
    id: '31f706b0-3d45-47ec-b87c-0ec6131ff766',
    applicationId: 'aws:lambda:eu-west-1:77',
    applicationName: 'java-prod',
    traceId: '1-6411a931-5ce3583012a68c407907d29f',
    transactionId: 'f5c1378e-ce2e-44ad-ba46-ce9828c7adae',
    domainName: '',
    className: 'Method',
    parentSpanId: 'e0bc5610-7558-4340-b804-d4e398243098',
    operationName: 'validateNotEmptyString',
    startTimestamp: 1678879025825,
    finishTimestamp: 1678879025825,
    duration: 0,
    tags: {
      'method.lines': [
        {
          duration: 0,
          line: 73,
          localVars: [
            { name: 'str', type: 'java.lang.String', value: '3' },
            { name: 'errorMessage', type: 'java.lang.String', value: 'Team id cannot be empty!' },
          ],
        },
        {
          duration: 0,
          line: 78,
          localVars: [
            { name: 'str', type: 'java.lang.String', value: '3' },
            { name: 'errorMessage', type: 'java.lang.String', value: 'Team id cannot be empty!' },
          ],
        },
      ],
      'method.return_value': {},
      'method.args': [
        { name: 'str', type: 'java.lang.String', value: '3' },
        { name: 'errorMessage', type: 'java.lang.String', value: 'Team id cannot be empty!' },
      ],
      'method.startLine': 72,
      'method.source':
        '    private void validateNotEmptyString(String str, String errorMessage) {\n        if (StringUtils.isNullOrEmpty(str)) {\n            DemoIllegalArgumentException demoIllegalArgumentException = new DemoIllegalArgumentException(errorMessage);\n            logger.error(errorMessage, demoIllegalArgumentException);\n            throw demoIllegalArgumentException;\n        }\n    }\n',
    },
  },
  {
    id: '7eaafb4a-15d9-4589-b33f-ad669f255ee4',
    applicationId: 'aws:lambda:eu-west-1:77',
    applicationName: 'java-prod',
    traceId: '1-6411a931-5ce3583012a68c407907d29f',
    transactionId: 'f5c1378e-ce2e-44ad-ba46-ce9828c7adae',
    domainName: '',
    className: 'Method',
    parentSpanId: '9a23a36a-d32b-496e-bb00-f7602661705a',
    operationName: 'getFromCache',
    startTimestamp: 1678879025825,
    finishTimestamp: 1678879025832,
    duration: 7,
    tags: {
      'method.lines': [
        { duration: 0, line: 95, localVars: [{ name: 'id', type: 'java.lang.String', value: '3' }] },
        {
          duration: 6,
          nextSpanIds: ['2a423feb-d494-416a-8e3d-ac58afff2ebe'],
          line: 99,
          localVars: [{ name: 'id', type: 'java.lang.String', value: '3' }],
        },
      ],
      'method.return_value': {},
      'method.args': [{ name: 'id', type: 'java.lang.String', value: '3' }],
      'method.startLine': 93,
      'method.source':
        '    private Team getFromCache(String id) {\n        // Simulate random cache misses :)\n        if (random.nextInt(4) == 0) {\n            doProcess(5);\n            return null;\n        } else {\n            return cacheManager.get(CACHE_NAME, id);\n        }\n    }\n',
    },
  },
  {
    id: '2a423feb-d494-416a-8e3d-ac58afff2ebe',
    applicationId: 'aws:lambda:eu-west-1:77',
    applicationName: 'java-prod',
    traceId: '1-6411a931-5ce3583012a68c407907d29f',
    transactionId: 'f5c1378e-ce2e-44ad-ba46-ce9828c7adae',
    domainName: 'Cache',
    className: 'Redis',
    parentSpanId: '7eaafb4a-15d9-4589-b33f-ad669f255ee4',
    operationName: 'localhost',
    startTimestamp: 1678879025825,
    finishTimestamp: 1678879025825,
    duration: 0,
    tags: {
      'db.instance': 'localhost',
      'db.type': 'redis',
      'redis.host': 'localhost',
      'db.statement': 'GET "team::3"',
      'operation.type': 'READ',
      'redis.command': 'GET "team::3"',
      'redis.command.type': 'GET',
      'topology.vertex': true,
      'db.statement_type': 'READ',
    },
  },
  {
    id: '40e08b9e-4b84-444a-a7c5-ee2359db680e',
    applicationId: 'aws:lambda:eu-west-1:77',
    applicationName: 'java-prod',
    traceId: '1-6411a931-5ce3583012a68c407907d29f',
    transactionId: 'f5c1378e-ce2e-44ad-ba46-ce9828c7adae',
    domainName: '',
    className: 'Method',
    parentSpanId: '9a23a36a-d32b-496e-bb00-f7602661705a',
    operationName: 'get',
    startTimestamp: 1678879025832,
    finishTimestamp: 1678879025888,
    duration: 56,
    tags: {
      'method.lines': [
        { duration: 0, line: 41, localVars: [{ name: 'id', type: 'java.lang.String', value: '3' }] },
        { duration: 0, line: 43, localVars: [{ name: 'id', type: 'java.lang.String', value: '3' }] },
        {
          duration: 55,
          nextSpanIds: ['517015c4-eeb3-46c1-b1c5-40129400abda'],
          line: 44,
          localVars: [{ name: 'id', type: 'java.lang.String', value: '3' }],
        },
        {
          duration: 0,
          line: 49,
          localVars: [
            { name: 'id', type: 'java.lang.String', value: '3' },
            {
              name: 'getItemResult',
              type: 'com.amazonaws.services.dynamodbv2.model.GetItemResult',
              value: {
                item: { creationTime: {}, name: {}, id: {} },
                sdkResponseMetadata: { metadata: {} },
                sdkHttpMetadata: { httpHeaders: {}, httpStatusCode: 200 },
              },
            },
          ],
        },
        {
          duration: 0,
          line: 50,
          localVars: [
            { name: 'id', type: 'java.lang.String', value: '3' },
            {
              name: 'getItemResult',
              type: 'com.amazonaws.services.dynamodbv2.model.GetItemResult',
              value: {
                item: { creationTime: {}, name: {}, id: {} },
                sdkResponseMetadata: { metadata: {} },
                sdkHttpMetadata: { httpHeaders: {}, httpStatusCode: 200 },
              },
            },
            {
              name: 'item',
              type: 'java.util.HashMap',
              value: { creationTime: { n: '1678877820177' }, name: { s: 'Team-643358844' }, id: { s: '3' } },
            },
          ],
        },
        {
          duration: 0,
          line: 54,
          localVars: [
            { name: 'id', type: 'java.lang.String', value: '3' },
            {
              name: 'getItemResult',
              type: 'com.amazonaws.services.dynamodbv2.model.GetItemResult',
              value: {
                item: { creationTime: {}, name: {}, id: {} },
                sdkResponseMetadata: { metadata: {} },
                sdkHttpMetadata: { httpHeaders: {}, httpStatusCode: 200 },
              },
            },
            {
              name: 'item',
              type: 'java.util.HashMap',
              value: { creationTime: { n: '1678877820177' }, name: { s: 'Team-643358844' }, id: { s: '3' } },
            },
          ],
        },
        {
          duration: 0,
          line: 56,
          localVars: [
            { name: 'id', type: 'java.lang.String', value: '3' },
            {
              name: 'getItemResult',
              type: 'com.amazonaws.services.dynamodbv2.model.GetItemResult',
              value: {
                item: { creationTime: {}, name: {}, id: {} },
                sdkResponseMetadata: { metadata: {} },
                sdkHttpMetadata: { httpHeaders: {}, httpStatusCode: 200 },
              },
            },
            {
              name: 'item',
              type: 'java.util.HashMap',
              value: { creationTime: { n: '1678877820177' }, name: { s: 'Team-643358844' }, id: { s: '3' } },
            },
            {
              name: 'team',
              type: 'Team',
              value: { creationTime: 1678877820177, name: 'Team-643358844', id: '3' },
            },
          ],
        },
        {
          duration: 0,
          line: 58,
          localVars: [
            { name: 'id', type: 'java.lang.String', value: '3' },
            {
              name: 'getItemResult',
              type: 'com.amazonaws.services.dynamodbv2.model.GetItemResult',
              value: {
                item: { creationTime: {}, name: {}, id: {} },
                sdkResponseMetadata: { metadata: {} },
                sdkHttpMetadata: { httpHeaders: {}, httpStatusCode: 200 },
              },
            },
            {
              name: 'item',
              type: 'java.util.HashMap',
              value: { creationTime: { n: '1678877820177' }, name: { s: 'Team-643358844' }, id: { s: '3' } },
            },
            {
              name: 'team',
              type: 'Team',
              value: { creationTime: 1678877820177, name: 'Team-643358844', id: '3' },
            },
          ],
        },
      ],
      'method.return_value': {
        type: 'Team',
        value: { creationTime: 1678877820177, name: 'Team-643358844', id: '3' },
      },
      'method.args': [{ name: 'id', type: 'java.lang.String', value: '3' }],
      'method.startLine': 40,
      'method.source':
        '    public Team get(String id) {\n        logger.debug(String.format("Team with id %s has been requested", id));\n\n        GetItemResult getItemResult =\n                dynamoDBClient.getItem(\n                            TABLE_NAME,\n                            new HashMap<String, AttributeValue>() {{\n                                put("id", new AttributeValue().withS(id));\n                            }});\n        Map<String, AttributeValue> item = getItemResult.getItem();\n        if (item == null) {\n            return null;\n        }\n\n        Team team = attributesToTeam(item);\n\n        logger.debug(String.format("Team with id %s has been retrieved: %s", id, team));\n\n        return team;\n    }\n',
    },
  },
  {
    id: '517015c4-eeb3-46c1-b1c5-40129400abda',
    applicationId: 'aws:lambda:eu-west-1:77',
    applicationName: 'java-prod',
    traceId: '1-6411a931-5ce3583012a68c407907d29f',
    transactionId: 'f5c1378e-ce2e-44ad-ba46-ce9828c7adae',
    domainName: 'DB',
    className: 'AWS-DynamoDB',
    parentSpanId: '40e08b9e-4b84-444a-a7c5-ee2359db680e',
    operationName: 'team-lambda-java-prod',
    startTimestamp: 1678879025832,
    finishTimestamp: 1678879025888,
    duration: 56,
    tags: {
      'db.instance': 'dynamodb.eu-west-1.amazonaws.com',
      'aws.dynamodb.table.name': 'team-lambda-java-prod',
      'aws.request.name': 'GetItemRequest',
      'db.type': 'aws-dynamodb',
      'aws.service.name': 'AWS-DynamoDB',
      'aws.dynamodb.request.throttled': false,
      'operation.type': 'READ',
      'db.statement': '{"key":{"id":{"s":"3"}}}',
      'topology.vertex': true,
      'db.statement_type': 'READ',
    },
  },
  {
    id: '32450ee9-8ab1-4cf3-ac45-c33861c4bae3',
    applicationId: 'aws:lambda:eu-west-1:77',
    applicationName: 'java-prod',
    traceId: '1-6411a931-5ce3583012a68c407907d29f',
    transactionId: 'f5c1378e-ce2e-44ad-ba46-ce9828c7adae',
    domainName: '',
    className: 'Method',
    parentSpanId: '9a23a36a-d32b-496e-bb00-f7602661705a',
    operationName: 'searchTeamProfile',
    startTimestamp: 1678879025888,
    finishTimestamp: 1678879025938,
    duration: 50,
    tags: {
      'method.lines': [
        { duration: 0, line: 104, localVars: [{ name: 'id', type: 'java.lang.String', value: '3' }] },
        {
          duration: 49,
          nextSpanIds: ['02673647-61c8-4284-ab71-78d7bb5db630'],
          line: 106,
          localVars: [
            { name: 'id', type: 'java.lang.String', value: '3' },
            {
              name: 'client',
              type: 'org.apache.http.impl.client.InternalHttpClient',
              value: {
                cookieSpecRegistry: { map: {} },
                execChain: { redirectStrategy: {}, log: {}, requestExecutor: {}, routePlanner: {} },
                connManager: { connectionOperator: {}, isShutDown: false, configData: {}, log: {}, pool: {} },
                closeables: [{}],
                authSchemeRegistry: { map: {} },
                log: { name: 'org.apache.http.impl.client.InternalHttpClient' },
                defaultConfig: {
                  circularRedirectsAllowed: false,
                  authenticationEnabled: true,
                  staleConnectionCheckEnabled: false,
                  connectTimeout: -1,
                  socketTimeout: -1,
                  relativeRedirectsAllowed: true,
                  connectionRequestTimeout: -1,
                  contentCompressionEnabled: true,
                  expectContinueEnabled: false,
                  redirectsEnabled: true,
                  maxRedirects: 50,
                },
                routePlanner: {},
                cookieStore: { lock: {} },
                credentialsProvider: {},
              },
            },
          ],
        },
        {
          duration: 0,
          line: 109,
          localVars: [
            { name: 'id', type: 'java.lang.String', value: '3' },
            {
              name: 'client',
              type: 'org.apache.http.impl.client.InternalHttpClient',
              value: {
                cookieSpecRegistry: { map: {} },
                execChain: { redirectStrategy: {}, log: {}, requestExecutor: {}, routePlanner: {} },
                connManager: { connectionOperator: {}, isShutDown: false, configData: {}, log: {}, pool: {} },
                closeables: [{}],
                authSchemeRegistry: { map: {} },
                log: { name: 'org.apache.http.impl.client.InternalHttpClient' },
                defaultConfig: {
                  circularRedirectsAllowed: false,
                  authenticationEnabled: true,
                  staleConnectionCheckEnabled: false,
                  connectTimeout: -1,
                  socketTimeout: -1,
                  relativeRedirectsAllowed: true,
                  connectionRequestTimeout: -1,
                  contentCompressionEnabled: true,
                  expectContinueEnabled: false,
                  redirectsEnabled: true,
                  maxRedirects: 50,
                },
                routePlanner: {},
                cookieStore: { lock: {} },
                credentialsProvider: {},
              },
            },
          ],
        },
        {
          duration: 0,
          line: 110,
          localVars: [
            { name: 'id', type: 'java.lang.String', value: '3' },
            {
              name: 'client',
              type: 'org.apache.http.impl.client.InternalHttpClient',
              value: {
                cookieSpecRegistry: { map: {} },
                execChain: { redirectStrategy: {}, log: {}, requestExecutor: {}, routePlanner: {} },
                connManager: { connectionOperator: {}, isShutDown: false, configData: {}, log: {}, pool: {} },
                closeables: [{}],
                authSchemeRegistry: { map: {} },
                log: { name: 'org.apache.http.impl.client.InternalHttpClient' },
                defaultConfig: {
                  circularRedirectsAllowed: false,
                  authenticationEnabled: true,
                  staleConnectionCheckEnabled: false,
                  connectTimeout: -1,
                  socketTimeout: -1,
                  relativeRedirectsAllowed: true,
                  connectionRequestTimeout: -1,
                  contentCompressionEnabled: true,
                  expectContinueEnabled: false,
                  redirectsEnabled: true,
                  maxRedirects: 50,
                },
                routePlanner: {},
                cookieStore: { lock: {} },
                credentialsProvider: {},
              },
            },
          ],
        },
      ],
      'method.return_value': {},
      'method.args': [{ name: 'id', type: 'java.lang.String', value: '3' }],
      'method.startLine': 103,
      'method.source':
        '    private void searchTeamProfile(String id) {\n        HttpClient client = HttpClientBuilder.create().build();\n        try {\n            client.execute(new HttpGet("http://jsonplaceholder.typicode.com/albums/" + id));\n        } catch (IOException e) {\n            logger.error("Error occurred while searching team profile with id " + id, e);\n        }\n    }\n',
    },
  },
  {
    id: '02673647-61c8-4284-ab71-78d7bb5db630',
    applicationId: 'aws:lambda:eu-west-1:77',
    applicationName: 'java-prod',
    traceId: '1-6411a931-5ce3583012a68c407907d29f',
    transactionId: 'f5c1378e-ce2e-44ad-ba46-ce9828c7adae',
    domainName: 'Web',
    className: 'HTTP',
    parentSpanId: '32450ee9-8ab1-4cf3-ac45-c33861c4bae3',
    operationName: 'jsonplaceholder.typicode.com/albums',
    startTimestamp: 1678879025904,
    finishTimestamp: 1678879025938,
    duration: 34,
    tags: {
      'http.status_code': 200,
      'operation.type': 'GET',
      'http.query_params': '',
      'http.path': '/albums/3',
      'http.url': 'jsonplaceholder.typicode.com/albums/3',
      'topology.vertex': true,
      'http.method': 'GET',
      'http.host': 'jsonplaceholder.typicode.com',
      'trace.links': ['722bc60e-4409-4fb2-8bcb-a115df5eaf55::02673647-61c8-4284-ab71-78d7bb5db630'],
    },
  },
];
